// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    /* For Prisma 7 'db push', we want the Direct connection.
       We will point this to DIRECT_URL for now to get your 
       tables created.
    */
    url: env("DIRECT_URL"),
  },
  migrations: {
    // This tells Prisma how to execute your seed file
    seed: 'ts-node --compiler-options {"module":"CommonJS"} db/seed3.ts',
  },
});
